language: python
dist: trusty

# addons:
#   apt:
#     sources:
#       - google-chrome
#     packages:
#       - google-chrome-stable

python:
  - "2.7"

services:
  - docker

install:
  ## - pip install flake8==3.3.0
  ## - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  - sudo rm /etc/apt/sources.list.d/docker.list
  # - sudo apt-get purge -y mysql-common mysql-server mysql-client
  # - nvm install v7.10.0
  # - wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py
  # - sudo python install.py --develop --user travis --without-bench-setup
  # - sudo pip install -e ~/bench

  # - rm $TRAVIS_BUILD_DIR/.git/shallow
  # - bash $TRAVIS_BUILD_DIR/travis/bench_init.sh
  - docker --version
  - docker pull vishaljsesh/erpnext-travis
  # - cp -r $TRAVIS_BUILD_DIR/test_sites/test_site ~/frappe-bench/sites/
  - docker run -d -it --name erpnext-travis -p 8000:8000 -p 9000:9000 -p 6787:6787 -v $TRAVIS_BUILD_DIR:/home/frappe/erpnext vishaljsesh/erpnext-travis:latest

before_script:
  # - wget http://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip
  # - unzip chromedriver_linux64.zip
  # - sudo apt-get install libnss3
  # - sudo apt-get --only-upgrade install google-chrome-stable
  # - sudo cp chromedriver /usr/local/bin/.
  # - sudo chmod +x /usr/local/bin/chromedriver
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
  # - sleep 3
  - docker exec -i erpnext-travis bash -c "wget http://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip"
  - docker exec -i erpnext-travis bash -c "unzip chromedriver_linux64.zip"
  - docker exec -i erpnext-travis bash -c "apt-get install libnss3"
  - docker exec -i erpnext-travis bash -c "apt-get install google-chrome-stable xvfb"
  - docker exec -i erpnext-travis bash -c "cp chromedriver /usr/local/bin/."
  - docker exec -i erpnext-travis bash -c "chmod +x /usr/local/bin/chromedriver"
  - docker exec -i erpnext-travis bash -c "export DISPLAY=:99.0"
  - docker exec -i erpnext-travis bash -c "service mysql restart"
  # - mysql -u root -ptravis -e 'create database test_frappe'

  # - echo "USE mysql;\nCREATE USER 'test_frappe'@'localhost' IDENTIFIED BY 'test_frappe';\nFLUSH PRIVILEGES;\n" | mysql -u root -ptravis
  # - echo "USE mysql;\nGRANT ALL PRIVILEGES ON \`test_frappe\`.* TO 'test_frappe'@'localhost';\n" | mysql -u root -ptravis

  # - cd ~/frappe-bench
  # - bench get-app erpnext $TRAVIS_BUILD_DIR
  # - bench use test_site
  # - bench reinstall --yes
  # - bench build
  # - bench scheduler disable
  # - bench start &

  # - PR_BRANCH_HEAD=$(docker exec -itu frappe erpnext-travis bash -c "cd ~/erpnext && echo $(git rev-parse HEAD)")
  - PR_BRANCH_HEAD=$(docker exec -itu frappe erpnext-travis bash -c "cd ~/erpnext && git rev-parse HEAD") 
  - docker exec -itu frappe erpnext-travis bash -c "cd ~/frappe-bench/apps/erpnext && git remote add test ~/erpnext/ && git fetch --unshallow test && git checkout -b test -t test/$TRAVIS_BRANCH"
  # - CURRENT_BRANCH_HEAD=$(docker exec -itu frappe erpnext-travis bash -c "cd ~/frappe-bench/apps/erpnext && echo git rev-parse HEAD")
  - CURRENT_BRANCH_HEAD=$(docker exec -itu frappe erpnext-travis bash -c "cd ~/frappe-bench/apps/erpnext && git rev-parse HEAD")
  - set -e
  - diff <( echo \"$PR_BRANCH_HEAD\" ) <( echo \"$CURRENT_BRANCH_HEAD\" )
  # - bench get-app erpnext $TRAVIS_BUILD_DIR
  - docker exec -itu frappe erpnext-travis bash -c "cd ~/frappe-bench && bench use test_site"
  # - bench reinstall --yes
  - docker exec -itu frappe erpnext-travis bash -c "cd ~/frappe-bench/apps/frappe && git config --global user.email 'you@example.com' && git config --global user.name 'Your Name' && git add . && git stash && git pull --rebase upstream develop"
  - docker exec -itu frappe erpnext-travis bash -c "cd ~/frappe-bench && bench setup requirements && bench build"
  - docker exec -itu frappe erpnext-travis bash -c "cd ~/frappe-bench && bench reinstall --yes && bench migrate"
  - docker exec -itu frappe erpnext-travis bash -c "cd ~/frappe-bench && bench scheduler disable"
  # - docker exec -itu frappe erpnext-travis bash -c "cd ~/frappe-bench && bench start &"
  - docker exec -idu frappe erpnext-travis bash -c "cd ~/frappe-bench && bench start"
  # - docker exec -itu frappe erpnext-travis bash -c "cd ~/frappe-bench && sleep 10"
  
  - sleep 10 
  - docker exec -it erpnext-travis bash -c "service xvfb restart"

jobs:
  include:
    - stage: test
      script:
        - set -e
        # - bench run-tests
        - docker exec -iu frappe erpnext-travis bash -c "cd ~/frappe-bench && bench run-tests"
      env: Server Side Test
    - # stage
      script:
        # - bench --verbose run-setup-wizard-ui-test
        # - bench execute erpnext.setup.utils.enable_all_roles_and_domains
        # - bench run-ui-tests --app erpnext
        - docker exec -iu frappe erpnext-travis bash -c "cd ~/frappe-bench && bench --verbose run-setup-wizard-ui-test"
        - docker exec -iu frappe erpnext-travis bash -c "cd ~/frappe-bench && bench execute erpnext.setup.utils.enable_all_roles_and_domains"
        - docker exec -iu frappe erpnext-travis bash -c "cd ~/frappe-bench && bench run-ui-tests --app erpnext"
      env: Client Side Test
    - # stage
      script:
        - docker exec -iu frappe erpnext-travis bash -c "cd ~/frappe-bench && bench --verbose run-setup-wizard-ui-test"
        - docker exec -iu frappe erpnext-travis bash -c "cd ~/frappe-bench && bench execute erpnext.setup.utils.enable_all_roles_and_domains"
        - docker exec -iu frappe erpnext-travis bash -c "cd ~/frappe-bench && bench run-ui-tests --app erpnext --test-list erpnext/tests/ui/tests2.txt"
      env: Client Side Test - 2
    - # stage
      script:
        - docker exec -iu frappe erpnext-travis bash -c "cd ~/frappe-bench && bench --verbose run-setup-wizard-ui-test"
        - docker exec -iu frappe erpnext-travis bash -c "cd ~/frappe-bench && docker exec -iu frappe erpnext-travis bash -c "cd ~/frappe-bench && bench execute erpnext.setup.utils.enable_all_roles_and_domains"
        - docker exec -iu frappe erpnext-travis bash -c "cd ~/frappe-bench && bench run-ui-tests --app erpnext --test-list erpnext/tests/ui/agriculture.txt"
      env: Agriculture Client Side Test
    - # stage
      script:
        - docker exec -iu frappe erpnext-travis bash -c "cd ~/frappe-bench && wget http://build.erpnext.com/20171108_190013_955977f8_database.sql.gz"
        - docker exec -iu frappe erpnext-travis bash -c "cd ~/frappe-bench && bench --force restore ~/frappe-bench/20171108_190013_955977f8_database.sql.gz --mariadb-root-password travis"
        - docker exec -iu frappe erpnext-travis bash -c "cd ~/frappe-bench && bench migrate"
      env: Patch Testing
